### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by jamesmcclain** [mojodna/osm2orc#12]
Running [0.5.2](https://github.com/mojodna/osm2orc/commit/9a46819d555a78db8d60cd3e6c98ab7c538c4863) on [this file](http://download.geofabrik.de/south-america/peru-180101.osm.pbf) produces the following error message:

```bash
osm2orc-0.5.2/bin% ./osm2orc ~/Downloads/peru-180101.osm.pbf ~/Downloads/peru-180101.orc     
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454)
        at de.topobyte.osm4j.pbf.protobuf.Osmformat$DenseInfo.getUid(Osmformat.java:5954)
        at de.topobyte.osm4j.pbf.seq.PrimParser.convert(PrimParser.java:360)
        at de.topobyte.osm4j.pbf.seq.PbfIterator.pushNodes(PbfIterator.java:181)
        at de.topobyte.osm4j.pbf.seq.PbfIterator.advanceBlock(PbfIterator.java:149)
        at de.topobyte.osm4j.pbf.seq.PbfIterator.tryAdvanceBlock(PbfIterator.java:120)
        at de.topobyte.osm4j.pbf.seq.PbfIterator.hasNext(PbfIterator.java:77)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at net.mojodna.osm2orc.standalone.OsmPbf2Orc.convert(OsmPbf2Orc.java:123)
        at net.mojodna.osm2orc.Osm2Orc.main(Osm2Orc.java:39)
osm2orc-0.5.2/bin% 
```

The same behavior can also be observed with 0.5.1.

**Comment by sethfitz** [comment]
Good find. There's something weird about that PBF (the `-latest` version of Peru doesn't exhibit the same problem), but it's in the wild, so...

Fixed in https://github.com/topobyte/osm4j-pbf/pull/6

**Comment by jamesmcclain** [comment]
Thank you, much appreciated.
